add error handling for bash features

diff --git a/create-dev-env b/create-dev-env
--- a/create-dev-env
+++ b/create-dev-env
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 set -e
 
+if [ "${BASH_VERSINFO:-0}" -lt 4 ]; then
+    echo "Error: Bash version 4 required. If on macos, install bash from homebrew: brew install bash"
+    exit 1
+fi
+
 if ! [ -x "$(command -v limactl)" ]; then
     echo "no limactl command found. Install lima from https://lima-vm.io/docs/installation/"
     exit 1
